name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to Hetzner server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script: |
          cd /sites/juystinDev
          git pull origin main
          docker stop juystindev || true
          docker rm juystindev || true
          docker rmi 'juystindev' || true
          docker build -t 'juystindev' .
          docker run --detach -p 3000:3000 'juystindev'
          
