name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to Hetzner server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script: |
          cd /sites/BrutusMapsBackend
          git pull origin main
          docker rmi 'brutusmapsbackend'
          docker build -t 'brutusmapsbackend' .
          docker run --detach new_image_name
          
